# Variables and types

In [9]:
# float - real numbers
my_float = 1.8

# int - integer numbers
my_int = 3

# str - string (text)
my_str = 'A text'

# bool - True or False
my_bool = True

types = [type(my_float), type(my_int), type(my_str), type(my_bool)]
types

[float, int, str, bool]

# Lists

In [16]:
family = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]

type(family)

list

## List of lists

In [17]:
fam2 = [
    ["liz", 1.73],
    ["emma", 1.68],
    ["mom", 1.71],
    ["dad", 1.89]
]

fam2

[['liz', 1.73], ['emma', 1.68], ['mom', 1.71], ['dad', 1.89]]

## Subsetting lists

In [45]:
family = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]

# First index is 0
print("Index 3 is", family[3])
print("Last index is", family[-1])

Index 3 is 1.68
Last index is 1.89


## List slicing

[start : end]

| start | end |
| --- | --- |
| inclusive | exclusive |

In [26]:
print(family[3:5])
print(family[1:4])
print(family[:4])
print(family[5:])

[1.68, 'mom']
[1.73, 'emma', 1.68]
['liz', 1.73, 'emma', 1.68]
[1.71, 'dad', 1.89]


## Manipulating lists

### Changing list elements

In [31]:
family = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]

print(family)

family[7] = 1.86
family[0:2] = ["lisa", 1.74]

family

['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]


['lisa', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]

### Adding and removing elements

In [35]:
del(family[2:3])
print(family)

family = family + ["me", 1.79]
print(family)

['lisa', 1.74, 'dad', 1.86, 'me', 1.79]
['lisa', 1.74, 'dad', 1.86, 'me', 1.79, 'me', 1.79]


# Functions and Packages

## Functions

In [43]:
family = [1.73, 1.68, 1.71, 1.89]
print("Max value is ", max(family))
print("Rounded 1.68 with 1 digit is", round(1.68, 1))
print("Rounded 1.68 with default digit (0) is", round(1.68))

Max value is  1.89
Rounded 1.68 with 1 digit is 1.7
Rounded 1.68 with default digit (0) is 2


## Methods

Everything is an object in Python. Objects have methods. Methods are functions that belong to objects.

List methods

In [44]:
family = ['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

print("Index of 'mom' is", family.index("mom"))
print("Count of 1.73 is", family.count(1.73))


Index of 'mom' is 4
Count of 1.73 is 1


String methods

In [47]:
sister = 'liz'
print(sister.capitalize())
print(sister.replace("z", "sa"))

Liz
lisa


## Packages

Examples of packages available in Python:
* NumPy
* Matplotlib
* scikit-learn

In [1]:
import numpy

numpy.array([1, 2, 3])

array([1, 2, 3])

In [2]:
import numpy as np

np.array([1, 2, 3])

array([1, 2, 3])

In [3]:
from numpy import array

array([1, 2, 3])

array([1, 2, 3])

# Numpy

## Introduction

Better than lists for numerical data. Numpy arrays are faster and more compact than lists.
* Mathematical operations over collections
* Speed

Problem: limits of lists

In [4]:
height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]
weight / height ** 2 # Error

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

Solution:NumPy
* Numeric Python
* Alternative to Python List: NumPy Array
* Calculations over entire arrays
* Easy and Fast
* Installation
  * `pip3 install numpy`

In [8]:
import numpy as np

height = [1.73, 1.68, 1.71, 1.89, 1.79]
weight = [65.4, 59.2, 63.6, 88.4, 68.7]

np_height = np.array(height)
np_weight = np.array(weight)

bmi = np_weight / np_height ** 2

bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

Different types, different behavior

In [10]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

print(python_list + python_list)
print(numpy_array + numpy_array)

[1, 2, 3, 1, 2, 3]
[2 4 6]


## NumPy subsetting

In [11]:
bmi = array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

print(bmi[1])
print(bmi > 23)
print(bmi[bmi > 23])

20.97505669
[False False False  True False]
[24.7473475]


## 2D Numpy Arrays

Types of NumPy arrays

In [12]:
import numpy as np

np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])

type(np_height)

numpy.ndarray

2D NumPy Arrays

In [13]:
np_2d = np.array([
    [1.73, 1.68, 1.71, 1.89, 1.79],
    [65.4, 59.2, 63.6, 88.4, 68.7]
])

np_2d.shape

(2, 5)

Subsetting

In [17]:
print(np_2d[0])

print(np_2d[0][2])

print(np_2d[0, 2])

print(np_2d[:, 1:3])

print(np_2d[1, :])

[1.73 1.68 1.71 1.89 1.79]
1.71
1.71
[[ 1.68  1.71]
 [59.2  63.6 ]]
[65.4 59.2 63.6 88.4 68.7]


## Numpy: Basic Statistics

City-wide survey

In [20]:
import numpy as np

np_city = np.array([
    [1.64, 71.78],
    [1.37, 63.35],
    [1.6 , 55.09],
    [2.04, 74.85],
    [2.04, 68.72],
    [2.01, 73.57]
])

print(np.mean(np_city[:, 0]))
print(np.median(np_city[:, 0]))

1.7833333333333332
1.8249999999999997
